// <auto-generated />
namespace Siteware.Prototipo.DAL.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriacaoDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriacaoDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201605070008411_CriacaoDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
